ernestio/ernest

config/config-store/config.json
definition.yml

deploying repos for: 
- ernestio/ernest#7
- ernestio/ernest#8
- ernestio/ernest#9

adding elbs

---

definition.yml

depreciating network builder and adapter

---

definition.yml

implements: ernestio/ernest#61

removing instance adapter/builder

---

definition.yml

Fixes : https://github.com/ernestio/ernest/issues/70

Deploy s3-all-aws-connector

---

definition.yml

removing firewall builder/adapter

---

definition.yml

Fixes : https://github.com/ernestio/ernest/issues/84

Enable logger on docker deploys

---

docker-compose.yml

This reverts commit 36d6f19b95207086dd7dc5acbb4407c28006d99b.

Revert "Logger to create default file"

---

definition.yml

removed unused builder/adapters

---

definition.yml

Fixes : https://github.com/ernestio/ernest/issues/81

Deploy route53-all-aws-connector

---

definition.yml

removing router builder and adapter

---

definition.yml

Fixes [this](https://github.com/ernestio/ernest/issues/139) by merging all nat-*-aws-connectors on a single [nat-all-aws-connector](https://github.com/ernestio/nat-all-aws-connector) service

[WIP] Use nat-all-aws-connector instead of one per subject

---

definition.yml

Fixes https://github.com/ernestio/ernest/issues/107

[#ERNEST-107] : Deploy rds-all-aws-connector

---

definition.yml

Fixes : https://github.com/ernestio/ernest/issues/173

[#ERNEST-173] : Logger to persist adapters

---

setup

Fixes : https://github.com/ernestio/ernest/issues/155

[#ERNEST-155] : Allow user to introduce default admin credentials

---

setup

Fixes : https://github.com/ernestio/ernest/issues/186

Hide password on the input

---

setup

Fixes : https://github.com/ernestio/ernest/issues/92

Cross platform sed on setup script

---

definition.yml
setup

Fixes : https://github.com/ernestio/ernest/issues/197

[#ERNEST-197] : Allow environment overload with "-E" option

---

setup

Fixes : https://github.com/ernestio/ernest/issues/199

Automatically generate crypto key

---

docker-compose.yml

Bump from 1.10 to 1.11 to the Dockerfile.

Dockerfile Version

---

definition.yml

implements ernestio/ernest#232

adding find subscriptions to all-all-aws-connector

---

.gitignore
setup
upgrade

Implements https://github.com/ernestio/ernest/issues/249 with upgrade command

[#ERNEST-249] : Fixes ernest/249 by adding upgrade command

---

setup

Prevent accepting empty credentials

---

definition.yml
template.yml

Implements https://github.com/ernestio/ernest/issues/296

[#ERNEST-296] : deploy usage-store

---

definition.yml
template.yml

removed adapter, builder, workflow-manager, aws-mapper, vcloud-mapper and redis, added scheduler

Updating docker compose setup for new/removed repos

---

internal/definitions/service-revert.yml
internal/definitions/service-revert2.yml
internal/features/cli/service_revert.feature

Tests for ernestio/ernest-cli#92

Add tests for CLI revert feature

---

internal/features/cli/info.feature
internal/features/steps/step_definitions.go

Fixes ernestio/ernest-cli/pull/100

F cli info version 588

---

setup

Fix output escaping on older versions of Bash

---

internal/features/cli/service_destroy.feature

Fixes: https://github.com/ernestio/ernest/issues/836

Check live stream output when destroying an evironment tests

---

internal/features/cli/service_import.feature

[#ERNEST-837] : Fix import not working pre-release bug

---

definition.yml

added inspec/compliance service prototype to definition.yml

---

config/nginx/ernest.licensed
config/nginx/ernest.local
definition.yml
template.yml

added notification service to enterprise
